project:
  type: website

website:
  description: "A blog built with Quarto"
  site-url: https://your-website-url.example.com # you must change this appropriately for RSS feeds to work properly
  title: "Sarah's Blog"
  favicon: "pandaa.jpg"
  navbar:
    logo: "pandaa.jpg"
    right:
      - href: about.qmd
        text: "About Me"
      - icon: linkedin
        href: https://www.linkedin.com/in/xingyulee/
      - icon: github
        href: https://github.com/Xingyuii/
      - icon: instagram
        href: https://instagram.com/sarah.l133
      - icon: wechat
        href: "wechat.JPG"
        target: "_blank"
      - icon: youtube
        href: https://www.youtube.com/@XingyuSarah
      - icon: envelope
        href: "mailto:xingyu.sarah@gmail.com"
      - text: "![](/icons/bilibili.svg){height=18px}"
        href: "https://b23.tv/7RiB25o"
      - text: "![](/icons/xiaohongshu.svg){height=20px}"
        href: "https://xhslink.com/m/41beRsIE9P9"



  comments:
      giscus:
        repo: "Xingyuii/my-quant-blog"
        repo-id: "R_kgDOQWHABw"
        category: "Announcements"
        category-id: "DIC_kwDOQWHAB84Cx0aS"
        mapping: "pathname"
        reactions-enabled: true
        input-position: "bottom"
        theme:
          light: "light"  
          dark: "dark"   

format:
  html:
    theme:
      light: [cosmo, brand]
      dark: [cyborg, brand]
    css: styles.css
    include-after-body: _post-footer.html



