on:
  push:
    branches: main

name: Publish Quarto Website

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-cli-action@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python Dependencies
        run: |
          pip install numpy matplotlib

      - name: Render and Publish Website
        uses: quarto-dev/quarto-cli-action@v2
        with:
          command: publish gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}